// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Counter: typeof import('./src/components/Counter.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    TheNavMenu: typeof import('./src/components/TheNavMenu.vue')['default']
    TheTitleBar: typeof import('./src/components/TheTitleBar.vue')['default']
  }
}

export { }
