export default [
  { key: 'title', identifier: 'T' },
  { key: 'meter', identifier: 'M' },
  { key: 'quarterNote', identifier: 'L' },
  { key: 'key', identifier: 'K' },
  { key: 'quantize', identifier: 'Q' },
  { key: 'notes', identifier: 'N' },
  { key: 'history', identifier: 'H' },
  { key: 'composer', identifier: 'C' },
  { key: 'type', identifier: 'R' },
  { key: 'origin', identifier: 'O' },
  { key: 'source', identifier: 'S' },
  { key: 'recordings', identifier: 'D' },
  { key: 'transcription', identifier: 'Z' },
]
